using System.Text;
using System.Text.RegularExpressions;

namespace Pkc.Knowledge;

public sealed partial class ProductFeatureMarkdownRenderer
{
    public string GetRelativePath(ProductFeature feature) =>
        $"knowledge/features/{Slug(feature.Area)}/{feature.Category}.md";

    public string Render(ProductFeature feature)
    {
        ArgumentNullException.ThrowIfNull(feature);

        var builder = new StringBuilder();
        builder.AppendLine("---");
        builder.AppendLine($"id: {Yaml(feature.Id)}");
        builder.AppendLine($"title: {Yaml(feature.Title)}");
        builder.AppendLine($"area: {Yaml(feature.Area)}");
        builder.AppendLine($"category: {Yaml(feature.Category)}");
        builder.AppendLine($"authority: {Yaml(feature.Authority)}");
        builder.AppendLine("generated: true");
        builder.AppendLine("coverage:");
        foreach (var coverage in feature.Coverage)
        {
            builder.AppendLine($"  - {coverage}");
        }
        builder.AppendLine("---");
        builder.AppendLine();
        builder.AppendLine($"# {feature.Title}");
        builder.AppendLine();
        builder.AppendLine("> Product-level view synthesized from grounded workflows. It describes observed implementation, not business-approved intent.");
        builder.AppendLine();
        builder.AppendLine(feature.Summary);
        builder.AppendLine();

        builder.AppendLine("## Workflows");
        builder.AppendLine();
        foreach (var workflow in feature.Workflows)
        {
            var action = workflow.Id.Split(':', StringSplitOptions.RemoveEmptyEntries).LastOrDefault() ?? workflow.Title;
            var link = $"../../workflows/{Slug(feature.Area)}/{Slug(action)}.md";
            builder.AppendLine($"### [{workflow.Title}]({link})");
            builder.AppendLine();

            if (workflow.UiSteps.Count > 0)
            {
                builder.AppendLine("User path:");
                foreach (var step in workflow.UiSteps)
                {
                    builder.AppendLine($"- {step}");
                }
                builder.AppendLine();
            }

            if (workflow.EntryPoints.Count > 0)
            {
                builder.AppendLine("Backend entry:");
                foreach (var entry in workflow.EntryPoints)
                {
                    builder.AppendLine($"- {entry}");
                }
                builder.AppendLine();
            }
        }

        AppendListSection(builder, "Permissions", feature.Permissions);
        AppendListSection(builder, "Observed business rules", feature.Rules);
        AppendListSectionIfAny(builder, "Observed capability flow", AggregateWorkflowItems(feature, workflow => workflow.Flow));
        AppendListSectionIfAny(builder, "Observed state changes", AggregateWorkflowItems(feature, workflow => workflow.StateChanges));
        AppendListSectionIfAny(builder, "Observed side effects", AggregateWorkflowItems(feature, workflow => workflow.SideEffects));
        AppendListSection(builder, "Important unknowns", feature.Unknowns);

        builder.AppendLine("## How to use this file");
        builder.AppendLine();
        builder.AppendLine("- Use this file for product-level questions about the feature.");
        builder.AppendLine("- `Observed capability flow` is a selective application-level collaboration view; open the workflow file for the complete grounded flow and source evidence.");
        builder.AppendLine("- Open the linked workflow Markdown when a question needs exact UI steps, backend behavior, state changes, side effects, or source evidence.");
        builder.AppendLine("- Do not infer missing business intent from code-observed behavior.");

        return builder.ToString();
    }

    public string RenderIndex(ProductFeatureDocument document)
    {
        ArgumentNullException.ThrowIfNull(document);

        var builder = new StringBuilder();
        builder.AppendLine("---");
        builder.AppendLine("id: \"pkc:knowledge-index\"");
        builder.AppendLine("title: \"Product Knowledge Index\"");
        builder.AppendLine("generated: true");
        builder.AppendLine("---");
        builder.AppendLine();
        builder.AppendLine("# Product Knowledge Index");
        builder.AppendLine();
        builder.AppendLine("This folder is a portable product knowledge pack generated by PKC.");
        builder.AppendLine();
        builder.AppendLine("## Instructions for AI assistants");
        builder.AppendLine();
        builder.AppendLine("- Start from this index for product questions.");
        builder.AppendLine("- Read the relevant feature file first, then open a linked workflow only when more detail is needed.");
        builder.AppendLine("- Treat `authority: code-observed` as current implementation evidence, not approved business intent.");
        builder.AppendLine("- Respect `Important unknowns`; do not invent missing UI, delivery, or business context.");
        builder.AppendLine("- Source evidence in workflow files exists for traceability; do not require the source repository for ordinary PO questions.");
        builder.AppendLine();

        AppendObservedSurface(builder, document);
        AppendConditionalSurface(builder, document);

        builder.AppendLine("## Product features");
        builder.AppendLine();

        foreach (var feature in document.Features)
        {
            var path = $"features/{Slug(feature.Area)}/{feature.Category}.md";
            builder.AppendLine($"- [{feature.Title}]({path}) — {feature.Workflows.Count} {(feature.Workflows.Count == 1 ? "workflow" : "workflows")}; coverage: {string.Join(", ", feature.Coverage)}");
        }

        if (document.Features.Count == 0)
        {
            builder.AppendLine("- No grounded product features were discovered.");
        }

        builder.AppendLine();
        builder.AppendLine("## Current knowledge boundary");
        builder.AppendLine();
        builder.AppendLine("PKC currently compiles backend C# and conservative static frontend evidence. Azure DevOps history, runtime UI confirmation, and business approval are separate future evidence sources unless explicitly present in feature files.");

        return builder.ToString();
    }

    private static IReadOnlyList<string> AggregateWorkflowItems(
        ProductFeature feature,
        Func<ProductWorkflowReference, IReadOnlyList<string>> selector)
    {
        var occurrences = feature.Workflows
            .SelectMany(workflow => selector(workflow)
                .Select(item => new WorkflowItem(WorkflowActionName(feature, workflow), item)))
            .ToArray();

        return occurrences
            .GroupBy(item => item.Value, StringComparer.Ordinal)
            .Select(group =>
            {
                var actions = group.Select(item => item.Action).Distinct(StringComparer.Ordinal).ToArray();
                return actions.Length > 1
                    ? group.Key
                    : $"{actions[0]}: {group.Key}";
            })
            .Distinct(StringComparer.Ordinal)
            .ToArray();
    }

    private static string WorkflowActionName(ProductFeature feature, ProductWorkflowReference workflow)
    {
        var prefix = feature.Area + " ";
        return workflow.Title.StartsWith(prefix, StringComparison.OrdinalIgnoreCase)
            ? workflow.Title[prefix.Length..]
            : workflow.Title;
    }

    private static void AppendObservedSurface(StringBuilder builder, ProductFeatureDocument document)
    {
        builder.AppendLine("## Observed capability surface");
        builder.AppendLine();
        builder.AppendLine("This is an implementation-observed orientation map. It groups discovered operations by capability area without inventing product intent or an unsupported user journey.");
        builder.AppendLine();

        if (document.Features.Count == 0)
        {
            builder.AppendLine("- No grounded capability surface was discovered.");
            builder.AppendLine();
            return;
        }

        foreach (var areaGroup in document.Features
                     .GroupBy(feature => feature.Area, StringComparer.Ordinal)
                     .OrderBy(group => group.Key, StringComparer.Ordinal))
        {
            var workflows = areaGroup.SelectMany(feature => feature.Workflows).ToArray();
            var entries = workflows
                .SelectMany(workflow => workflow.EntryPoints)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(entry => entry, StringComparer.Ordinal)
                .ToArray();
            var permissions = workflows
                .SelectMany(workflow => workflow.Permissions)
                .Distinct(StringComparer.Ordinal)
                .ToArray();

            builder.Append($"- **{areaGroup.Key}** — {workflows.Length} observed {(workflows.Length == 1 ? "workflow" : "workflows")}");
            if (entries.Length > 0)
            {
                builder.Append($"; entry points: {string.Join(", ", entries.Select(entry => $"`{entry}`"))}");
            }
            if (permissions.Length > 0)
            {
                builder.Append("; authorization/permission evidence present");
            }
            builder.AppendLine(".");
        }

        builder.AppendLine();
    }

    private static void AppendConditionalSurface(StringBuilder builder, ProductFeatureDocument document)
    {
        var conditionalRules = document.Features
            .SelectMany(feature => feature.Rules
                .Where(rule => rule.Contains("endpoint is registered only when", StringComparison.Ordinal))
                .Select(rule => (Feature: feature, Rule: rule)))
            .ToArray();

        if (conditionalRules.Length == 0)
        {
            return;
        }

        builder.AppendLine("## Conditional or environment-dependent surface");
        builder.AppendLine();
        foreach (var item in conditionalRules)
        {
            var path = $"features/{Slug(item.Feature.Area)}/{item.Feature.Category}.md";
            builder.AppendLine($"- [{item.Feature.Title}]({path}): {item.Rule}");
        }
        builder.AppendLine();
    }

    private static void AppendListSection(StringBuilder builder, string title, IReadOnlyList<string> items)
    {
        builder.AppendLine($"## {title}");
        builder.AppendLine();
        if (items.Count == 0)
        {
            builder.AppendLine("- No grounded information available yet.");
        }
        else
        {
            foreach (var item in items)
            {
                builder.AppendLine($"- {item}");
            }
        }
        builder.AppendLine();
    }

    private static void AppendListSectionIfAny(StringBuilder builder, string title, IReadOnlyList<string> items)
    {
        if (items.Count == 0)
        {
            return;
        }

        AppendListSection(builder, title, items);
    }

    private static string Yaml(string value) =>
        $"\"{value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal)}\"";

    private static string Slug(string value)
    {
        var slug = NonSlugRegex().Replace(value.ToLowerInvariant(), "-").Trim('-');
        return slug.Length == 0 ? "unknown" : slug;
    }

    private sealed record WorkflowItem(string Action, string Value);

    [GeneratedRegex("[^a-z0-9]+")]
    private static partial Regex NonSlugRegex();
}
