'use strict';
const fs = require('fs');
const path = require('path');

function analyze(rootArg, tsPath, apiFactsPath) {
  const root = path.resolve(rootArg);
  const ts = require(tsPath);
  const excluded = new Set(['.git','.pkc','bin','obj','node_modules','dist','build','coverage','knowledge']);
  const semanticScope = process.env.PKC_SEMANTIC_SCOPE ? JSON.parse(fs.readFileSync(process.env.PKC_SEMANTIC_SCOPE,'utf8')) : null;
  const excludedAreas = new Set(semanticScope ? semanticScope.excludedAreas : []);
  const withheldFiles = new Set(semanticScope ? semanticScope.withheldFiles : []);
  const apiFacts = JSON.parse(fs.readFileSync(apiFactsPath,'utf8'));
  const sourceCache = new Map();

  function norm(p){ return p.split(path.sep).join('/'); }
  function rel(p){ return norm(path.relative(root,p)); }
  function under(p){ const r=path.relative(root,path.resolve(p)); return r==='' || (r!=='..'&&!r.startsWith('..'+path.sep)&&!path.isAbsolute(r)); }
  function walk(dir,out=[]){ for(const e of fs.readdirSync(dir,{withFileTypes:true})){ if(e.isDirectory()&&excluded.has(e.name))continue; const f=path.join(dir,e.name); if(e.isDirectory()){ if(!excludedAreas.has(rel(f)))walk(f,out); } else if(e.isFile()&&e.name.endsWith('.ts')&&!e.name.endsWith('.d.ts')&&!withheldFiles.has(rel(f)))out.push(f);} return out; }
  function load(file){ file=path.resolve(file); if(!under(file)||!fs.existsSync(file))return null; if(sourceCache.has(file))return sourceCache.get(file); const text=fs.readFileSync(file,'utf8'); const sf=ts.createSourceFile(file,text,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS); sourceCache.set(file,{sf,text}); return {sf,text}; }
  function decorators(node){ return ts.canHaveDecorators&&ts.getDecorators ? ts.getDecorators(node)||[] : node.decorators||[]; }
  function propName(node){ if(!node)return null; if(ts.isIdentifier(node)||ts.isStringLiteral(node)||ts.isNumericLiteral(node))return node.text; return node.getText(); }
  function decCall(node,name){ return decorators(node).map(d=>d.expression).filter(ts.isCallExpression).find(c=>propName(c.expression)===name)||null; }
  function compMeta(cls){ const call=decCall(cls,'Component'); if(!call||call.arguments.length!==1||!ts.isObjectLiteralExpression(call.arguments[0]))return null; let selector=null,templateUrl=null; const importNames=[]; for(const p of call.arguments[0].properties){ if(!ts.isPropertyAssignment(p))continue; const n=propName(p.name); if(n==='selector'&&ts.isStringLiteral(p.initializer))selector=p.initializer.text; if(n==='templateUrl'&&ts.isStringLiteral(p.initializer))templateUrl=p.initializer.text; if(n==='imports'&&ts.isArrayLiteralExpression(p.initializer)){ for(const e of p.initializer.elements) if(ts.isIdentifier(e)) importNames.push(e.text); } } return selector&&templateUrl?{selector,templateUrl,importNames}:null; }
  function resolveModule(sourceFile,spec){ if(!spec.startsWith('.'))return null; const base=path.resolve(path.dirname(sourceFile.fileName),spec); for(const c of [base,base+'.ts',base+'.tsx',path.join(base,'index.ts')]) if(under(c)&&fs.existsSync(c)) return rel(c); return null; }
  function imports(sf){ const map=new Map(), amb=new Set(); for(const st of sf.statements){ if(!ts.isImportDeclaration(st)||!ts.isStringLiteral(st.moduleSpecifier)||!st.importClause?.namedBindings||!ts.isNamedImports(st.importClause.namedBindings))continue; const module=resolveModule(sf,st.moduleSpecifier.text); if(!module)continue; for(const el of st.importClause.namedBindings.elements){ const local=el.name.text, exp=el.propertyName?.text??local; if(amb.has(local))continue; const next={module,exp}; const old=map.get(local); if(old&&(old.module!==module||old.exp!==exp)){map.delete(local);amb.add(local);} else map.set(local,next); } } return map; }
  function locText(text,index,length,pathName){ let s=1; for(let i=0;i<index&&i<text.length;i++)if(text[i]==='\n')s++; let e=s; for(let i=index;i<Math.min(text.length,index+length);i++)if(text[i]==='\n')e++; return {path:pathName,startLine:s,endLine:e}; }
  function locNode(sf,node){ const a=sf.getLineAndCharacterOfPosition(node.getStart(sf)), b=sf.getLineAndCharacterOfPosition(node.getEnd()); return {path:rel(sf.fileName),startLine:a.line+1,endLine:b.line+1}; }
  function methodMap(cls){ const map=new Map(), amb=new Set(); for(const m of cls.members){ if(!ts.isMethodDeclaration(m)||!m.name||!m.body)continue; const n=propName(m.name); if(amb.has(n))continue; if(map.has(n)){map.delete(n);amb.add(n);} else map.set(n,m); } return map; }
  function outputMap(cls){ const map=new Map(),amb=new Set(); for(const p of cls.members){ if(!ts.isPropertyDeclaration(p)||!p.name)continue; const d=decCall(p,'Output'); if(!d)continue; let event=propName(p.name); if(d.arguments.length===1&&ts.isStringLiteral(d.arguments[0]))event=d.arguments[0].text; else if(d.arguments.length>0)continue; if(amb.has(event))continue; if(map.has(event)){map.delete(event);amb.add(event);} else map.set(event,{property:propName(p.name),node:p}); } return map; }
  function serviceFields(cls,imps){ const map=new Map(),amb=new Set(); for(const p of cls.members){ if(!ts.isPropertyDeclaration(p)||!p.name||!p.initializer||!ts.isCallExpression(p.initializer)||propName(p.initializer.expression)!=='inject'||p.initializer.arguments.length!==1||!ts.isIdentifier(p.initializer.arguments[0]))continue; const field=propName(p.name), type=p.initializer.arguments[0].text, imp=imps.get(type); if(!imp)continue; const ident=`${imp.module}#${imp.exp}`; if(amb.has(field))continue; if(map.has(field)&&map.get(field)!==ident){map.delete(field);amb.add(field);} else map.set(field,ident); } return map; }
  function componentEntries(){ const out=[]; for(const file of walk(root).sort()){ const loaded=load(file); if(!loaded)continue; const {sf}=loaded, imps=imports(sf); function visit(n){ if(ts.isClassDeclaration(n)&&n.name&&n.name.text.endsWith('Component')){ const meta=compMeta(n); if(meta){ const tpl=path.resolve(path.dirname(file),meta.templateUrl); if(under(tpl)&&fs.existsSync(tpl)){ const componentImports=new Set(); for(const name of meta.importNames){ const imp=imps.get(name); if(imp) componentImports.add(`${imp.module}#${imp.exp}`); } out.push({className:n.name.text,selector:meta.selector,identity:`${rel(file)}#${n.name.text}`,tsPath:rel(file),templatePath:rel(tpl),templateFull:tpl,sf,cls:n,methods:methodMap(n),outputs:outputMap(n),services:serviceFields(n,imps),componentImports}); } } } ts.forEachChild(n,visit);} visit(sf); } return out; }
  function buttonActions(c){ const html=fs.readFileSync(c.templateFull,'utf8'), out=[]; const re=/<button\b(?<attrs>[^>]*)>(?<body>[\s\S]*?)<\/button>/gi; let m; while((m=re.exec(html))){ const click=/\(click\)\s*=\s*["']\s*([A-Za-z_$][A-Za-z0-9_$]*)\s*\(\s*\)\s*["']/.exec(m.groups.attrs); if(!click)continue; const label=m.groups.body.replace(/<[^>]+>/g,' ').replace(/\{\{[^}]+\}\}/g,' ').replace(/\s+/g,' ').trim()||'button'; out.push({handler:click[1],label,source:locText(html,m.index,m[0].length,c.templatePath)}); } return out; }
  function emittedEvent(c,handler){ const method=c.methods.get(handler); if(!method)return null; const candidates=[]; function visit(n){ if(ts.isCallExpression(n)&&ts.isPropertyAccessExpression(n.expression)&&n.expression.name.text==='emit'&&ts.isPropertyAccessExpression(n.expression.expression)&&n.expression.expression.expression.kind===ts.SyntaxKind.ThisKeyword&&n.arguments.length===1&&ts.isArrayLiteralExpression(n.arguments[0])&&n.arguments[0].elements.length>=1&&ts.isStringLiteral(n.arguments[0].elements[0])){ const prop=n.expression.expression.name.text; for(const [event,o] of c.outputs) if(o.property===prop) candidates.push({event,discriminant:n.arguments[0].elements[0].text,source:locNode(c.sf,n)}); } ts.forEachChild(n,visit);} visit(method.body); return candidates.length===1?candidates[0]:null; }
  function parentBindings(parent,child,event){ const html=fs.readFileSync(parent.templateFull,'utf8'); const tagRe=new RegExp(`<${child.selector.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b(?<attrs>[\\s\\S]*?)>`,`gi`); const out=[]; let m; while((m=tagRe.exec(html))){ const bind=new RegExp(`\\(${event.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\)\\s*=\\s*["']\\s*([A-Za-z_$][A-Za-z0-9_$]*)\\s*\\(\\s*\\$event\\s*\\)\\s*["']`).exec(m.groups.attrs); if(bind)out.push({handler:bind[1],source:locText(html,m.index,m[0].length,parent.templatePath)}); } return out; }
  function dispatchTarget(parent,handler,discriminant){ const method=parent.methods.get(handler); if(!method||method.parameters.length<1||!ts.isArrayBindingPattern(method.parameters[0].name))return null; const elems=method.parameters[0].name.elements; if(elems.length<2||!ts.isBindingElement(elems[0])||!ts.isIdentifier(elems[0].name)||!ts.isBindingElement(elems[1])||!ts.isIdentifier(elems[1].name))return null; const eventVar=elems[0].name.text, idVar=elems[1].name.text, candidates=[]; function visit(n){ if(ts.isSwitchStatement(n)&&ts.isIdentifier(n.expression)&&n.expression.text===eventVar){ for(const clause of n.caseBlock.clauses){ if(!ts.isCaseClause(clause)||!ts.isStringLiteral(clause.expression)||clause.expression.text!==discriminant)continue; function cv(x){ if(ts.isCallExpression(x)&&ts.isPropertyAccessExpression(x.expression)&&x.expression.expression.kind===ts.SyntaxKind.ThisKeyword&&x.arguments.length===1&&ts.isIdentifier(x.arguments[0])&&x.arguments[0].text===idVar)candidates.push({method:x.expression.name.text,source:locNode(parent.sf,x)}); ts.forEachChild(x,cv);} for(const s of clause.statements)cv(s); } } ts.forEachChild(n,visit);} visit(method.body); return candidates.length===1?candidates[0]:null; }
  function serviceApi(parent,methodName){ const method=parent.methods.get(methodName); if(!method||method.parameters.length<1||!ts.isIdentifier(method.parameters[0].name))return null; const valueParam=method.parameters[0].name.text,candidates=[]; function unconditional(n){ for(let c=n.parent;c&&c!==method.body;c=c.parent){ if(ts.isArrowFunction(c)||ts.isFunctionExpression(c)||ts.isIfStatement(c)||ts.isConditionalExpression(c)||ts.isSwitchStatement(c)||ts.isForStatement(c)||ts.isForOfStatement(c)||ts.isForInStatement(c)||ts.isWhileStatement(c)||ts.isDoStatement(c))return false; } return true; } function visit(n){ if(ts.isCallExpression(n)&&unconditional(n)&&ts.isPropertyAccessExpression(n.expression)&&ts.isPropertyAccessExpression(n.expression.expression)&&n.expression.expression.expression.kind===ts.SyntaxKind.ThisKeyword&&n.arguments.length>=1&&ts.isIdentifier(n.arguments[0])&&n.arguments[0].text===valueParam){ const field=n.expression.expression.name.text, apiMethod=n.expression.name.text, owner=parent.services.get(field); if(owner){ const matches=apiFacts.filter(a=>a.ownerClass===owner&&a.container===apiMethod); if(matches.length===1)candidates.push({api:matches[0],field,apiMethod,owner,source:locNode(parent.sf,n)}); } } ts.forEachChild(n,visit);} visit(method.body); const uniq=new Map(candidates.map(c=>[c.api.id,c])); return uniq.size===1?[...uniq.values()][0]:null; }

  const components=componentEntries();
  const selectorCounts=new Map(); for(const c of components) selectorCounts.set(c.selector,(selectorCounts.get(c.selector)||0)+1);
  const facts=[],relations=[];
  for(const child of components){ if(selectorCounts.get(child.selector)!==1) continue; for(const action of buttonActions(child)){ const emitted=emittedEvent(child,action.handler); if(!emitted)continue; const bridges=[]; for(const parent of components){ if(parent===child||!parent.componentImports.has(child.identity))continue; for(const bind of parentBindings(parent,child,emitted.event)){ const dispatch=dispatchTarget(parent,bind.handler,emitted.discriminant); if(!dispatch)continue; const svc=serviceApi(parent,dispatch.method); if(!svc)continue; bridges.push({parent,bind,dispatch,svc}); } } const byApi=new Map(); for(const b of bridges){ if(!byApi.has(b.svc.api.id))byApi.set(b.svc.api.id,[]);byApi.get(b.svc.api.id).push(b); } if(byApi.size!==1)continue; const same=[...byApi.values()][0]; if(same.length!==1)continue; const b=same[0]; const id=`ui-event:${action.source.path}:${action.source.startLine}:ui-action:${action.label}`; facts.push({id,kind:'ui-action',name:action.label,container:child.className,source:action.source,metadata:{label:action.label,framework:'angular-static',handler:action.handler,analysisMode:'angular-output-event-bridge',analysisConfidence:'high',proof:'exact-child-click+output-literal+parent-binding+switch-dispatch+service-identity+api-method',outputEvent:emitted.event,eventDiscriminant:emitted.discriminant,parentComponent:b.parent.className,parentHandler:b.bind.handler,serviceType:b.svc.owner,apiMethod:b.svc.apiMethod,eventBridgeTrace:`${child.className}.${action.handler} -> ${emitted.event}(${emitted.discriminant}) -> ${b.parent.className}.${b.bind.handler} -> ${b.parent.className}.${b.dispatch.method} -> ${b.svc.apiMethod}`,childEmitLocation:`${emitted.source.path}:L${emitted.source.startLine}`,parentBindingLocation:`${b.bind.source.path}:L${b.bind.source.startLine}`,parentDispatchLocation:`${b.dispatch.source.path}:L${b.dispatch.source.startLine}`,serviceCallLocation:`${b.svc.source.path}:L${b.svc.source.startLine}`}}); relations.push({fromFactId:id,kind:'triggers-api',target:b.svc.api.id,source:action.source}); } }
  return {facts,relations};
}

if (require.main===module) process.stdout.write(JSON.stringify(analyze(process.argv[2],process.argv[3],process.argv[4])));
module.exports={analyze};
