<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>pkc</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Pkc.Core/Pkc.Core.csproj" />
    <ProjectReference Include="../Pkc.CSharp/Pkc.CSharp.csproj" />
    <ProjectReference Include="../Pkc.Knowledge/Pkc.Knowledge.csproj" />
  </ItemGroup>
</Project>
